services:
  - type: web
    name: ChatBot-AI
    runtime: python
    repo: https://github.com/wan-ilhami/ChatBot-AI-backend
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.backend:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
    plan: free
    region: singapore
    autoDeploy: true
